apiVersion: apps/v1
kind: Deployment
metadata:
  name: djs
  labels:
    app: djs
    plan: free
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: djs
        name: djs
    spec:
      containers:
        - name: free-djs
          image: samanzandh/djs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits:
              &a1
              cpu: "0.5"
              ephemeral-storage: 0.5G
              memory: 0.5G
            requests: *a1
          volumeMounts: []
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DEBUG
              value: "0"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes: []
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: djs-custom
spec:
  host: takhte-whiteboard.ir
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: djs
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: djs
  name: djs
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80
  selector:
    app: djs
  type: ClusterIP
