version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/src/appy
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis_server
      - rabbitmq
    tty: true
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=saman"
      - "POSTGRES_PASSWORD=123456789"
  redis_server:
    image: redis:6.2-alpine
    command: redis-server --save
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data/
  rabbitmq:
    image: rabbitmq:3.10.2-alpine
    ports:
      - 5672:5672
    command: rabbitmq-server
    volumes:
      - rabbit_data:/var/lib/rabbitmq/data/
    

volumes:
  postgres_data:
  redis_data:
  rabbit_data: