version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_server
    tty: true
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=saman"
      - "POSTGRES_PASSWORD=123456789"
  redis_server:
    image: redis:6.2-alpine
    command: redis-server --save
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data/

volumes:
  postgres_data:
  redis_data: