# Generated by Django 3.2.7 on 2022-03-25 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20220325_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeber',
            name='chatgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_chatgroup', to='messenger.chatgroup'),
        ),
        migrations.AlterField(
            model_name='memeber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
