# Generated by Django 3.2.7 on 2022-03-25 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0005_chatgroup_unread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memeber',
            unique_together={('user', 'chatgroup')},
        ),
    ]
