# Generated by Django 3.2.7 on 2022-03-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0007_remove_chatgroup_is_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savedmessages_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
