# Generated by Django 3.2.7 on 2022-03-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_savedmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedMessages',
        ),
    ]
