# Generated by Django 3.2.7 on 2022-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_chatgroup_is_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='unread',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
