# Generated by Django 3.2.7 on 2022-03-26 10:09

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_rename_memeber_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_id',
            field=models.CharField(default=messenger.models.generate_group_id, max_length=12, unique=True),
        ),
    ]
