# Generated by Django 3.2.7 on 2022-03-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_contact_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='membership',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_member', to='messenger.member'),
            preserve_default=False,
        ),
    ]
