# Generated by Django 3.2.7 on 2022-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_contact_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
