# Generated by Django 3.2.7 on 2022-03-30 16:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='photo',
            field=models.ImageField(blank=True, default='empty-profile.jpg', upload_to='media', validators=[users.models.validate_file_size, users.models.validate_file_extension]),
        ),
    ]
