# Generated by Django 3.2.7 on 2022-04-01 13:30

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_auto_20220330_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_id',
            field=models.CharField(default=messenger.models.generate_group_id, max_length=41, unique=True),
        ),
    ]
