# Generated by Django 3.2.7 on 2022-04-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_alter_chatgroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_last_read_message', to='messenger.message'),
        ),
    ]
