# Generated by Django 3.2.7 on 2022-04-10 15:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0023_alter_chatgroup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[users.models.validate_file_size, users.models.validate_file_extension]),
        ),
    ]
