# Generated by Django 3.2.7 on 2021-09-30 10:32

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="class",
            index=models.Index(
                name="class_id_idx",
                fields=["class_id"],
            ),
        ),
        AddIndexConcurrently(
            model_name="exam",
            index=models.Index(
                name="timestamp_idx",
                fields=["timestamp"],
            ),
        ),
        AddIndexConcurrently(
            model_name="grade",
            index=models.Index(
                name="grade_idx",
                fields=["grade"],
            ),
        ),
        AddIndexConcurrently(
            model_name="subject",
            index=models.Index(
                name="subject_idx",
                fields=["subject"],
            ),
        ),
    ]
