# Generated by Django 3.2.7 on 2021-09-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210930_1032'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='class',
            name='class_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grade_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_idx',
        ),
    ]
