# Generated by Django 3.2.7 on 2021-09-30 13:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210930_1053'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='class',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subject',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
    ]
