# Generated by Django 3.2.7 on 2021-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teacher_classes', to='mainapp.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='class_teachers', to='mainapp.Teacher'),
        ),
    ]
