# Generated by Django 3.2.7 on 2021-10-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211001_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examed_class',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='exam_class', to='mainapp.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='class_exams', to='mainapp.Exam'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_students', to='mainapp.Student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='class_subjects', to='mainapp.Subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to='mainapp.Teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='exam_grades', to='mainapp.Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='student_exams', to='mainapp.Exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subject_teacher', to='mainapp.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teacher_classes', to='mainapp.Class'),
        ),
    ]
