# Generated by Django 3.2.7 on 2021-10-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211001_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examed_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_class', to='mainapp.class'),
        ),
    ]
