# Generated by Django 3.2.7 on 2021-10-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20211001_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='mainapp.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='mainapp.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='tested_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_class', to='mainapp.class'),
        ),
    ]
