# Generated by Django 3.2.7 on 2021-10-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211003_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='tested_class',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_class',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='exam_class', to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='full_score',
            field=models.DecimalField(decimal_places=4, default=20, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam', to='mainapp.exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='class_yeachers', to='mainapp.Teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='grade_user', to='mainapp.student'),
        ),
    ]
