# Generated by Django 3.2.7 on 2021-10-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211014_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_class', to='mainapp.class'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='full_score',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam', to='mainapp.exam'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_user', to='mainapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='mainapp.class'),
        ),
    ]
