# Generated by Django 3.2.7 on 2021-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_grade_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='tested_class',
            new_name='exam_class',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
        migrations.AddField(
            model_name='exam',
            name='full_score',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
    ]
