# Generated by Django 3.2.7 on 2021-10-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211009_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.OneToOneField(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam', to='mainapp.exam'),
        ),
    ]
