# Generated by Django 3.2.7 on 2021-10-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_grade_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam', to='mainapp.exam'),
        ),
    ]
