# Generated by Django 3.2.7 on 2021-10-17 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0019_alter_teacher_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'support')},
        ),
    ]
