# Generated by Django 3.2.7 on 2021-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_grade_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
