# Generated by Django 3.2.7 on 2021-10-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20211022_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='mainapp.teacher'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'teacher')},
        ),
    ]
