# Generated by Django 3.2.7 on 2021-10-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20211025_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('teacher', "has teachers' permissions"),)},
        ),
    ]
