# Generated by Django 3.2.7 on 2021-11-07 07:58

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('mainapp', '0029_auto_20211102_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateField(db_index=True),
        ),
        AddIndexConcurrently(
            model_name='exam',
            index=models.Index(
                name="timestamp_idx",
                fields=["timestamp"]
            )
        )
    ]
