# Generated by Django 3.2.7 on 2021-11-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_exam_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='timestamp_idx',
        ),
    ]
