# Generated by Django 3.2.7 on 2021-12-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_exam_timestamp_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Courses'},
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='mainapp.class', verbose_name='Student Class'),
        ),
    ]
