# Generated by Django 3.2.7 on 2021-12-23 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_alter_article_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subjects',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=5),
            preserve_default=False,
        ),
    ]
