# Generated by Django 3.2.7 on 2022-04-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20220128_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
