# Generated by Django 3.2.7 on 2022-04-08 11:34

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0005_alter_school_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0043_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=5)),
                ('text', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'T'), ('user_type', 'SS'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_school', to='supports.school')),
            ],
        ),
    ]
