# Generated by Django 3.2.7 on 2022-04-08 15:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_user'),
        ('mainapp', '0044_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_class', to='mainapp.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_subject', to='mainapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_teacher', to='teachers.teacher')),
            ],
        ),
    ]
