# Generated by Django 3.2.7 on 2022-04-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
    ]
