# Generated by Django 3.2.7 on 2022-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('student', 'Student'),)},
        ),
    ]
