# Generated by Django 3.2.7 on 2022-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
