# Generated by Django 3.2.7 on 2022-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_exam_visible_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='full_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exam',
            name='visible_to_students',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
