# Generated by Django 3.2.7 on 2022-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='class_subjects', to='mainapp.Subject'),
        ),
    ]
