# Generated by Django 3.2.7 on 2021-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210930_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='../../static/assets/img/icons/common/empty-profile.jpg', null=True, upload_to=''),
        ),
    ]
