# Generated by Django 3.2.7 on 2021-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='/static/assets/img/icons/common/empty-profile.jpg', null=True, upload_to='media'),
        ),
    ]
