# Generated by Django 3.2.7 on 2021-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('IT', 'IT staff'), ('P', 'principal'), ('O', 'others')], max_length=3),
        ),
    ]
