# Generated by Django 3.2.7 on 2021-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='j', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('IT', 'IT staff'), ('P', 'principal'), ('O', 'others')], max_length=3, null=True),
        ),
    ]
