# Generated by Django 3.2.7 on 2021-10-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211013_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('SS', 'support staff'), ('P', 'principal')], max_length=3, null=True),
        ),
    ]
