# Generated by Django 3.2.7 on 2021-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211016_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
