# Generated by Django 3.2.7 on 2021-10-30 19:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211018_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True, upload_to='media', validators=[users.models.validate_file_extension, users.models.validate_file_size]),
        ),
    ]
