# Generated by Django 3.2.7 on 2022-03-22 15:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220106_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='empty-profile.jpg', upload_to='media', validators=[users.models.validate_file_size]),
        ),
    ]
