# Generated by Django 3.2.7 on 2022-03-25 16:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[users.models.validate_file_size]),
        ),
    ]
