# Generated by Django 3.2.7 on 2022-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('SS', 'support staff')], max_length=3),
        ),
    ]
