# Generated by Django 3.2.7 on 2022-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User Model', 'verbose_name_plural': 'User Model'},
        ),
    ]
