# Generated by Django 3.2.7 on 2021-11-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20211102_1758'),
        ('teachers', '0002_delete_teacher'),
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
