# Generated by Django 3.2.7 on 2022-03-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0003_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('support', "has support staff's permissions"), ('create_group', 'can create groups in the messenger'))},
        ),
    ]
