# Generated by Django 3.2.7 on 2022-04-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0005_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('support', "has support staff's permissions"), ('create_api', 'has permission to create in api'))},
        ),
    ]
